import { Router, type IRouter } from "express";
import healthRouter from "./health";
import versionRouter from "./version";
import stationsRouter from "./stations";
import reviewsRouter from "./reviews";
import favoritesRouter from "./favorites";
import statsRouter from "./stats";
import invoicesRouter from "./invoices";
import paymentsRouter from "./payments";
import globalStationsRouter from "./globalStations";
import chargingSessionEmailRouter from "./chargingSessionEmail";
import analyticsRouter from "./analytics";
import gasStationsRouter from "./gasStations";
import evStationsRouter from "./evStations";
import pricingRouter from "./pricing";
import gasPricesRouter from "./gasPrices";
import operatorApplicationsRouter from "./operatorApplications";
import userProfileRouter from "./userProfile";
import billingRouter from "./billing";
import buttonConfigsRouter from "./buttonConfigs";
import geocodeRouter from "./geocode";
import routingRouter from "./routing";
import fleetRouter from "./fleet";
import cpoRouter from "./cpo";
import photosRouter from "./photos";
import checkinsRouter from "./checkins";
import citiesRouter from "./cities";
import tripPlanRouter from "./tripPlan";
import enrichRouter from "./enrich";
import savedTripsRouter from "./savedTrips";
import statusReportsRouter from "./statusReports";
import transitlandRouter from "./transitland";
import locationPhotosRouter from "./locationPhotos";
import nearbyPlacesRouter from "./nearbyPlaces";
import householdRouter from "./household";
import adminReviewRouter from "./adminReview";
import clerkConfigRouter from "./clerkConfig";
import corsAdminRouter from "./corsAdmin";
import rankingAdminRouter from "./rankingAdmin";
import companionRouter from "./companion";
import ownershipReportRouter from "./ownershipReport";
import vehicleCatalogRouter from "./vehicleCatalog";
import stationsMatchRouter from "./stationsMatch";

const router: IRouter = Router();

router.use(healthRouter);
router.use(versionRouter);
router.use(stationsMatchRouter); // must precede stationsRouter (avoids :id matching "match")
router.use(stationsRouter);
router.use(reviewsRouter);
router.use(favoritesRouter);
router.use(statsRouter);
router.use(invoicesRouter);
router.use(paymentsRouter);
router.use(globalStationsRouter);
router.use(chargingSessionEmailRouter);
router.use(analyticsRouter);
router.use(gasStationsRouter);
router.use(evStationsRouter);
router.use(pricingRouter);
router.use(gasPricesRouter);
router.use(operatorApplicationsRouter);
router.use(userProfileRouter);
router.use(billingRouter);
router.use(buttonConfigsRouter);
router.use(geocodeRouter);
router.use(routingRouter);
router.use(fleetRouter);
router.use(cpoRouter);
router.use(photosRouter);
router.use(checkinsRouter);
router.use(citiesRouter);
router.use(tripPlanRouter);
router.use(enrichRouter);
router.use(savedTripsRouter);
router.use(statusReportsRouter);
router.use(transitlandRouter);
router.use(locationPhotosRouter);
router.use(nearbyPlacesRouter);
router.use(householdRouter);
router.use(adminReviewRouter);
router.use(clerkConfigRouter);
router.use(corsAdminRouter);
router.use(rankingAdminRouter);
router.use(companionRouter);
router.use(ownershipReportRouter);
router.use(vehicleCatalogRouter);

export default router;
